name: Release & Deploy

on:
  workflow_dispatch:

jobs:
  job_release:
    runs-on: ubuntu-latest
    environment: prod1
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Login to AB Internal Registry
        uses: docker/login-action@v4
        with:
          registry: https://${{ vars.AB_INT_REGISTRY_HOST }}
          username: ${{ vars.AB_INT_REGISTRY_USER }}
          password: ${{ secrets.AB_INT_REGISTRY_PASS }}

      - name: "Install PNPM"
        uses: pnpm/action-setup@v6
        with:
          version: latest
    
      - name: "Install Dependencies"
        run: pnpm install
    
      - name: "Process Release"
        id: release
        run: |
          git config user.name "notedeck[bot]"
          git config user.email "76795128+notedeck[bot]@users.noreply.github.com"

          pnpm changeset:version

          git add -A

          if git diff --cached --quiet && git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "ci: Process release"
          git push origin HEAD:main

          VERSION=$(node -p "require('./package.json').version")
          echo "semver=${VERSION}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Vite App"
        run: pnpm build

        # == FOR REGISTRY DEPLOYMENT ONLY ==
      - name: Docker Build & Push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: |
            ${{ vars.AB_INT_REGISTRY_HOST }}/notes:latest
            ${{ vars.AB_INT_REGISTRY_HOST }}/notes:${{ steps.release.outputs.semver }}

        # == FOR NOTEDECK.DEV DEPLOYMENT ONLY ==
      - name: "[ 7 ] Deploy to Azure Static Web Apps"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_STONE_029252903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          skip_app_build: true
          output_location: ""
