name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  job_validation:
    runs-on: ubuntu-latest
    steps:
      - name: "[ 1 ] Checkout"
        uses: actions/checkout@v3

      - name: "[ 2 ] Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: "[ 3 ] Install PNPM"
        uses: pnpm/action-setup@v6
        with:
          version: latest
    
      - name: "[ 4 ] Install Deps"
        run: pnpm install

      - name: "[ 5A ] Validate: ESLint"
        run: pnpm lint:ci

      - name: "[ 5B ] Validate: TS Types"
        run: pnpm types:ci
      
      - name: "[ 5C ] Validate: Prettier"
        run: pnpm format:ci
        