name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  job_validation:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Install PNPM"
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: "Install Deps"
        run: pnpm install

      - name: "Validate: Linting"
        run: pnpm lint:ci

      - name: "Validate: TS Checks"
        run: pnpm types:ci

      - name: "Validate: Code Formatting"
        run: pnpm format:ci
